
services:
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:rw
    ports:
      - "8000:80"
    
  node:
    build: ./
    volumes:
      - ./:/www
      #current directory to container directory
    